export interface Player {
  name: string;
  country: string;
  role: 'Batter' | 'Bowler' | 'All-Rounder' | 'WK-Batter';
}

export interface TeamSquad {
  teamAbbr: string;
  batters: Player[];
  allRounders: Player[];
  bowlers: Player[];
}

export const TEAMS_SQUAD: TeamSquad[] = [
  {
    teamAbbr: 'CSK',
    batters: [
      { name: 'Ruturaj Gaikwad', country: 'India', role: 'Batter' },
      { name: 'MS Dhoni', country: 'India', role: 'WK-Batter' },
      { name: 'Sanju Samson', country: 'India', role: 'WK-Batter' },
      { name: 'Dewald Brevis', country: 'South Africa', role: 'Batter' },
      { name: 'Ayush Mhatre', country: 'India', role: 'Batter' },
      { name: 'Kartik Sharma', country: 'India', role: 'WK-Batter' },
      { name: 'Sarfaraz Khan', country: 'India', role: 'Batter' },
      { name: 'Urvil Patel', country: 'India', role: 'WK-Batter' },
    ],
    allRounders: [
      { name: 'Jamie Overton', country: 'England', role: 'All-Rounder' },
      { name: 'Ramakrishna Ghosh', country: 'India', role: 'All-Rounder' },
      { name: 'Prashant Veer', country: 'India', role: 'All-Rounder' },
      { name: 'Matthew William Short', country: 'Australia', role: 'All-Rounder' },
      { name: 'Aman Khan', country: 'India', role: 'All-Rounder' },
      { name: 'Zak Foulkes', country: 'Australia', role: 'All-Rounder' },
      { name: 'Shivam Dube', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Khaleel Ahmed', country: 'India', role: 'Bowler' },
      { name: 'Noor Ahmad', country: 'Afghanistan', role: 'Bowler' },
      { name: 'Anshul Kamboj', country: 'India', role: 'Bowler' },
      { name: 'Mukesh Choudhary', country: 'India', role: 'Bowler' },
      { name: 'Shreyas Gopal', country: 'India', role: 'Bowler' },
      { name: 'Gurjapneet Singh', country: 'India', role: 'Bowler' },
      { name: 'Akeal Hosein', country: 'West Indies', role: 'Bowler' },
      { name: 'Matt Henry', country: 'New Zealand', role: 'Bowler' },
      { name: 'Rahul Chahar', country: 'India', role: 'Bowler' },
      { name: 'Spencer Johnson', country: 'Australia', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'DC',
    batters: [
      { name: 'KL Rahul', country: 'India', role: 'WK-Batter' },
      { name: 'Karun Nair', country: 'India', role: 'Batter' },
      { name: 'David Miller', country: 'South Africa', role: 'Batter' },
      { name: 'Ben Duckett', country: 'England', role: 'WK-Batter' },
      { name: 'Pathum Nissanka', country: 'Sri Lanka', role: 'Batter' },
      { name: 'Sahil Parakh', country: 'India', role: 'Batter' },
      { name: 'Prithvi Shaw', country: 'India', role: 'Batter' },
      { name: 'Abishek Porel', country: 'India', role: 'WK-Batter' },
      { name: 'Tristan Stubbs', country: 'South Africa', role: 'WK-Batter' },
    ],
    allRounders: [
      { name: 'Axar Patel', country: 'India', role: 'All-Rounder' },
      { name: 'Sameer Rizvi', country: 'India', role: 'All-Rounder' },
      { name: 'Ashutosh Sharma', country: 'India', role: 'All-Rounder' },
      { name: 'Vipraj Nigam', country: 'India', role: 'All-Rounder' },
      { name: 'Ajay Mandal', country: 'India', role: 'All-Rounder' },
      { name: 'Tripurana Vijay', country: 'India', role: 'All-Rounder' },
      { name: 'Madhav Tiwari', country: 'India', role: 'All-Rounder' },
      { name: 'Nitish Rana', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Mitchell Starc', country: 'Australia', role: 'Bowler' },
      { name: 'T. Natarajan', country: 'India', role: 'Bowler' },
      { name: 'Mukesh Kumar', country: 'India', role: 'Bowler' },
      { name: 'Dushmantha Chameera', country: 'Sri Lanka', role: 'Bowler' },
      { name: 'Auqib Nabi', country: 'India', role: 'Bowler' },
      { name: 'Lungisani Ngidi', country: 'South Africa', role: 'Bowler' },
      { name: 'Kyle Jamieson', country: 'New Zealand', role: 'Bowler' },
      { name: 'Kuldeep Yadav', country: 'India', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'GT',
    batters: [
      { name: 'Shubman Gill', country: 'India', role: 'Batter' },
      { name: 'Jos Buttler', country: 'England', role: 'WK-Batter' },
      { name: 'Kumar Kushagra', country: 'India', role: 'WK-Batter' },
      { name: 'Anuj Rawat', country: 'India', role: 'WK-Batter' },
      { name: 'Tom Banton', country: 'England', role: 'WK-Batter' },
      { name: 'Glenn Phillips', country: 'New Zealand', role: 'Batter' },
      { name: 'Sai Sudharsan', country: 'India', role: 'Batter' },
    ],
    allRounders: [
      { name: 'Nishant Sindhu', country: 'India', role: 'All-Rounder' },
      { name: 'Washington Sundar', country: 'India', role: 'All-Rounder' },
      { name: 'Mohd. Arshad Khan', country: 'India', role: 'All-Rounder' },
      { name: 'Sai Kishore', country: 'India', role: 'All-Rounder' },
      { name: 'Jayant Yadav', country: 'India', role: 'All-Rounder' },
      { name: 'Jason Holder', country: 'West Indies', role: 'All-Rounder' },
      { name: 'Rahul Tewatia', country: 'India', role: 'All-Rounder' },
      { name: 'Shahrukh Khan', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Kagiso Rabada', country: 'South Africa', role: 'Bowler' },
      { name: 'Mohammed Siraj', country: 'India', role: 'Bowler' },
      { name: 'Prasidh Krishna', country: 'India', role: 'Bowler' },
      { name: 'Manav Suthar', country: 'India', role: 'Bowler' },
      { name: 'Gurnoor Singh Brar', country: 'India', role: 'Bowler' },
      { name: 'Ishant Sharma', country: 'India', role: 'Bowler' },
      { name: 'Ashok Sharma', country: 'India', role: 'Bowler' },
      { name: 'Luke Wood', country: 'England', role: 'Bowler' },
      { name: 'Kulwant Khejroliya', country: 'India', role: 'Bowler' },
      { name: 'Rashid Khan', country: 'Afghanistan', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'KKR',
    batters: [
      { name: 'Ajinkya Rahane', country: 'India', role: 'Batter' },
      { name: 'Rinku Singh', country: 'India', role: 'Batter' },
      { name: 'Angkrish Raghuvanshi', country: 'India', role: 'Batter' },
      { name: 'Manish Pandey', country: 'India', role: 'Batter' },
      { name: 'Finn Allen', country: 'New Zealand', role: 'WK-Batter' },
      { name: 'Tejasvi Singh', country: 'India', role: 'WK-Batter' },
      { name: 'Rahul Tripathi', country: 'India', role: 'Batter' },
      { name: 'Tim Seifert', country: 'New Zealand', role: 'WK-Batter' },
      { name: 'Rovman Powell', country: 'West Indies', role: 'Batter' },
    ],
    allRounders: [
      { name: 'Anukul Roy', country: 'India', role: 'All-Rounder' },
      { name: 'Cameron Green', country: 'Australia', role: 'All-Rounder' },
      { name: 'Sarthak Ranjan', country: 'India', role: 'All-Rounder' },
      { name: 'Daksh Kamra', country: 'India', role: 'All-Rounder' },
      { name: 'Rachin Ravindra', country: 'New Zealand', role: 'All-Rounder' },
      { name: 'Ramandeep Singh', country: 'India', role: 'All-Rounder' },
      { name: 'Sunil Narine', country: 'West Indies', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Blessing Muzarabani', country: 'Zimbabwe', role: 'Bowler' },
      { name: 'Vaibhav Arora', country: 'India', role: 'Bowler' },
      { name: 'Matheesha Pathirana', country: 'Sri Lanka', role: 'Bowler' },
      { name: 'Kartik Tyagi', country: 'India', role: 'Bowler' },
      { name: 'Prashant Solanki', country: 'India', role: 'Bowler' },
      { name: 'Saurabh Dubey', country: 'India', role: 'Bowler' },
      { name: 'Navdeep Saini', country: 'India', role: 'Bowler' },
      { name: 'Umran Malik', country: 'India', role: 'Bowler' },
      { name: 'Varun Chakaravarthy', country: 'India', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'LSG',
    batters: [
      { name: 'Rishabh Pant', country: 'India', role: 'WK-Batter' },
      { name: 'Aiden Markram', country: 'South Africa', role: 'Batter' },
      { name: 'Himmat Singh', country: 'India', role: 'Batter' },
      { name: 'Matthew Breetzke', country: 'South Africa', role: 'Batter' },
      { name: 'Mukul Choudhary', country: 'India', role: 'WK-Batter' },
      { name: 'Akshat Raghuwanshi', country: 'India', role: 'Batter' },
      { name: 'Josh Inglis', country: 'Australia', role: 'WK-Batter' },
      { name: 'Nicholas Pooran', country: 'West Indies', role: 'WK-Batter' },
    ],
    allRounders: [
      { name: 'Mitchell Marsh', country: 'Australia', role: 'All-Rounder' },
      { name: 'Abdul Samad', country: 'India', role: 'All-Rounder' },
      { name: 'Shahbaz Ahamad', country: 'India', role: 'All-Rounder' },
      { name: 'Arshin Kulkarni', country: 'India', role: 'All-Rounder' },
      { name: 'Wanindu Hasaranga', country: 'Sri Lanka', role: 'All-Rounder' },
      { name: 'Ayush Badoni', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Mohammad Shami', country: 'India', role: 'Bowler' },
      { name: 'Avesh Khan', country: 'India', role: 'Bowler' },
      { name: 'M. Siddharth', country: 'India', role: 'Bowler' },
      { name: 'Digvesh Singh', country: 'India', role: 'Bowler' },
      { name: 'Akash Singh', country: 'India', role: 'Bowler' },
      { name: 'Prince Yadav', country: 'India', role: 'Bowler' },
      { name: 'Arjun Tendulkar', country: 'India', role: 'Bowler' },
      { name: 'Anrich Nortje', country: 'South Africa', role: 'Bowler' },
      { name: 'Naman Tiwari', country: 'India', role: 'Bowler' },
      { name: 'Mayank Yadav', country: 'India', role: 'Bowler' },
      { name: 'Mohsin Khan', country: 'India', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'MI',
    batters: [
      { name: 'Rohit Sharma', country: 'India', role: 'Batter' },
      { name: 'Surya Kumar Yadav', country: 'India', role: 'Batter' },
      { name: 'Robin Minz', country: 'India', role: 'WK-Batter' },
      { name: 'Sherfane Rutherford', country: 'West Indies', role: 'Batter' },
      { name: 'Ryan Rickelton', country: 'South Africa', role: 'WK-Batter' },
      { name: 'Quinton de Kock', country: 'South Africa', role: 'WK-Batter' },
      { name: 'Danish Malewar', country: 'India', role: 'Batter' },
      { name: 'N. Tilak Varma', country: 'India', role: 'Batter' },
    ],
    allRounders: [
      { name: 'Hardik Pandya', country: 'India', role: 'All-Rounder' },
      { name: 'Naman Dhir', country: 'India', role: 'All-Rounder' },
      { name: 'Mitchell Santner', country: 'New Zealand', role: 'All-Rounder' },
      { name: 'Raj Angad Bawa', country: 'India', role: 'All-Rounder' },
      { name: 'Atharva Ankolekar', country: 'India', role: 'All-Rounder' },
      { name: 'Mayank Rawat', country: 'India', role: 'All-Rounder' },
      { name: 'Corbin Bosch', country: 'South Africa', role: 'All-Rounder' },
      { name: 'Will Jacks', country: 'England', role: 'All-Rounder' },
      { name: 'Shardul Thakur', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Trent Boult', country: 'New Zealand', role: 'Bowler' },
      { name: 'Mayank Markande', country: 'India', role: 'Bowler' },
      { name: 'Deepak Chahar', country: 'India', role: 'Bowler' },
      { name: 'Ashwani Kumar', country: 'India', role: 'Bowler' },
      { name: 'Raghu Sharma', country: 'India', role: 'Bowler' },
      { name: 'Mohammad Izhar', country: 'India', role: 'Bowler' },
      { name: 'Allah Ghazanfar', country: 'Afghanistan', role: 'Bowler' },
      { name: 'Jasprit Bumrah', country: 'India', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'PBKS',
    batters: [
      { name: 'Shreyas Iyer', country: 'India', role: 'Batter' },
      { name: 'Nehal Wadhera', country: 'India', role: 'Batter' },
      { name: 'Vishnu Vinod', country: 'India', role: 'WK-Batter' },
      { name: 'Harnoor Pannu', country: 'India', role: 'Batter' },
      { name: 'Pyla Avinash', country: 'India', role: 'Batter' },
      { name: 'Prabhsimran Singh', country: 'India', role: 'WK-Batter' },
      { name: 'Shashank Singh', country: 'India', role: 'Batter' },
    ],
    allRounders: [
      { name: 'Marcus Stoinis', country: 'Australia', role: 'All-Rounder' },
      { name: 'Harpreet Brar', country: 'India', role: 'All-Rounder' },
      { name: 'Marco Jansen', country: 'South Africa', role: 'All-Rounder' },
      { name: 'Azmatullah Omarzai', country: 'Afghanistan', role: 'All-Rounder' },
      { name: 'Priyansh Arya', country: 'India', role: 'All-Rounder' },
      { name: 'Musheer Khan', country: 'India', role: 'All-Rounder' },
      { name: 'Suryansh Shedge', country: 'India', role: 'All-Rounder' },
      { name: 'Mitch Owen', country: 'Australia', role: 'All-Rounder' },
      { name: 'Cooper Connolly', country: 'Australia', role: 'All-Rounder' },
      { name: 'Ben Dwarshuis', country: 'Australia', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Arshdeep Singh', country: 'India', role: 'Bowler' },
      { name: 'Yuzvendra Chahal', country: 'India', role: 'Bowler' },
      { name: 'Vyshak Vijaykumar', country: 'India', role: 'Bowler' },
      { name: 'Yash Thakur', country: 'India', role: 'Bowler' },
      { name: 'Xavier Bartlett', country: 'Australia', role: 'Bowler' },
      { name: 'Pravin Dubey', country: 'India', role: 'Bowler' },
      { name: 'Vishal Nishad', country: 'India', role: 'Bowler' },
      { name: 'Lockie Ferguson', country: 'New Zealand', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'RR',
    batters: [
      { name: 'Shubham Dubey', country: 'India', role: 'Batter' },
      { name: 'Vaibhav Suryavanshi', country: 'India', role: 'Batter' },
      { name: 'Donovan Ferreira', country: 'South Africa', role: 'WK-Batter' },
      { name: 'Lhuan-dre Pretorious', country: 'South Africa', role: 'WK-Batter' },
      { name: 'Ravi Singh', country: 'India', role: 'WK-Batter' },
      { name: 'Aman Rao Perala', country: 'India', role: 'Batter' },
      { name: 'Shimron Hetmyer', country: 'West Indies', role: 'Batter' },
      { name: 'Yashasvi Jaiswal', country: 'India', role: 'Batter' },
      { name: 'Dhruv Jurel', country: 'India', role: 'WK-Batter' },
    ],
    allRounders: [
      { name: 'Riyan Parag', country: 'India', role: 'All-Rounder' },
      { name: 'Yudhvir Singh Charak', country: 'India', role: 'All-Rounder' },
      { name: 'Ravindra Jadeja', country: 'India', role: 'All-Rounder' },
      { name: 'Dasun Shanaka', country: 'Sri Lanka', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Jofra Archer', country: 'England', role: 'Bowler' },
      { name: 'Tushar Deshpande', country: 'India', role: 'Bowler' },
      { name: 'Kwena Maphaka', country: 'South Africa', role: 'Bowler' },
      { name: 'Ravi Bishnoi', country: 'India', role: 'Bowler' },
      { name: 'Sushant Mishra', country: 'India', role: 'Bowler' },
      { name: 'Yash Raj Punja', country: 'India', role: 'Bowler' },
      { name: 'Vignesh Puthur', country: 'India', role: 'Bowler' },
      { name: 'Brijesh Sharma', country: 'India', role: 'Bowler' },
      { name: 'Adam Milne', country: 'New Zealand', role: 'Bowler' },
      { name: 'Kuldeep Sen', country: 'India', role: 'Bowler' },
      { name: 'Sandeep Sharma', country: 'India', role: 'Bowler' },
      { name: 'Nandre Burger', country: 'South Africa', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'RCB',
    batters: [
      { name: 'Rajat Patidar', country: 'India', role: 'Batter' },
      { name: 'Devdutt Padikkal', country: 'India', role: 'Batter' },
      { name: 'Virat Kohli', country: 'India', role: 'Batter' },
      { name: 'Phil Salt', country: 'England', role: 'WK-Batter' },
      { name: 'Jitesh Sharma', country: 'India', role: 'WK-Batter' },
      { name: 'Jordan Cox', country: 'England', role: 'WK-Batter' },
    ],
    allRounders: [
      { name: 'Krunal Pandya', country: 'India', role: 'All-Rounder' },
      { name: 'Swapnil Singh', country: 'India', role: 'All-Rounder' },
      { name: 'Tim David', country: 'Australia', role: 'All-Rounder' },
      { name: 'Romario Shepherd', country: 'West Indies', role: 'All-Rounder' },
      { name: 'Jacob Bethell', country: 'England', role: 'All-Rounder' },
      { name: 'Venkatesh Iyer', country: 'India', role: 'All-Rounder' },
      { name: 'Satvik Deswal', country: 'India', role: 'All-Rounder' },
      { name: 'Mangesh Yadav', country: 'India', role: 'All-Rounder' },
      { name: 'Vicky Ostwal', country: 'India', role: 'All-Rounder' },
      { name: 'Vihaan Malhotra', country: 'India', role: 'All-Rounder' },
      { name: 'Kanishk Chouhan', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Josh Hazlewood', country: 'Australia', role: 'Bowler' },
      { name: 'Rasikh Dar', country: 'India', role: 'Bowler' },
      { name: 'Suyash Sharma', country: 'India', role: 'Bowler' },
      { name: 'Bhuvneshwar Kumar', country: 'India', role: 'Bowler' },
      { name: 'Nuwan Thushara', country: 'Sri Lanka', role: 'Bowler' },
      { name: 'Abhinandan Singh', country: 'India', role: 'Bowler' },
      { name: 'Jacob Duffy', country: 'New Zealand', role: 'Bowler' },
      { name: 'Yash Dayal', country: 'India', role: 'Bowler' },
    ],
  },
  {
    teamAbbr: 'SRH',
    batters: [
      { name: 'Ishan Kishan', country: 'India', role: 'WK-Batter' },
      { name: 'Aniket Verma', country: 'India', role: 'Batter' },
      { name: 'Smaran Ravichandran', country: 'India', role: 'Batter' },
      { name: 'Salil Arora', country: 'India', role: 'WK-Batter' },
      { name: 'Heinrich Klaasen', country: 'South Africa', role: 'WK-Batter' },
      { name: 'Travis Head', country: 'Australia', role: 'Batter' },
    ],
    allRounders: [
      { name: 'Harshal Patel', country: 'India', role: 'All-Rounder' },
      { name: 'Kamindu Mendis', country: 'Sri Lanka', role: 'All-Rounder' },
      { name: 'Harsh Dubey', country: 'India', role: 'All-Rounder' },
      { name: 'Brydon Carse', country: 'England', role: 'All-Rounder' },
      { name: 'Shivang Kumar', country: 'India', role: 'All-Rounder' },
      { name: 'Krains Fuletra', country: 'India', role: 'All-Rounder' },
      { name: 'Liam Livingstone', country: 'England', role: 'All-Rounder' },
      { name: 'David Payne', country: 'England', role: 'All-Rounder' },
      { name: 'Abhishek Sharma', country: 'India', role: 'All-Rounder' },
      { name: 'Nitish Kumar Reddy', country: 'India', role: 'All-Rounder' },
    ],
    bowlers: [
      { name: 'Pat Cummins', country: 'Australia', role: 'Bowler' },
      { name: 'Zeeshan Ansari', country: 'India', role: 'Bowler' },
      { name: 'Jaydev Unadkat', country: 'India', role: 'Bowler' },
      { name: 'Eshan Malinga', country: 'India', role: 'Bowler' },
      { name: 'Sakib Hussain', country: 'India', role: 'Bowler' },
      { name: 'Onkar Tarmale', country: 'India', role: 'Bowler' },
      { name: 'Amit Kumar', country: 'India', role: 'Bowler' },
      { name: 'Praful Hinge', country: 'India', role: 'Bowler' },
      { name: 'Shivam Mavi', country: 'India', role: 'Bowler' },
    ],
  },
];

export function getTeamPlayers(teamAbbr: string): TeamSquad | undefined {
  return TEAMS_SQUAD.find(team => team.teamAbbr === teamAbbr);
}
